---
:global:
  main_branches:
    - main
  matrix_command:
  matrix_requires_yq: false
  build_runner: ubuntu-latest
  build_context: .
  build_file: Containerfile
  image_tag: 'ci/test:${{ github.sha }}'
  build_platforms:
  build_args: []

# Delete the following files if they exist in the repository
.markdownlint.json:
  delete: true
.github/workflows/ci.yaml:
  delete: true
.github/dependabot.yml:
  delete: true
.github/scripts/update_vulnerability_issue.rb:
  unmanaged: true
renovate.json:
  delete: true

.github/renovate.jsonc:
  renovate_custom_managers:
    - customType: regex
      datasourceTemplate: rubygems
      managerFilePatterns:
        - /build_versions.yaml/
      matchStrings:
        - "rubygem_(?<depName>[a-z0-9_-]+):\\s+'(?<currentValue>\\d+\\.\\d+\\.\\d+)'"
    - customType: regex
      datasourceTemplate: rubygems
      versioningTemplate: ruby
      managerFilePatterns:
        - /Containerfile/
      matchStrings:
        - >-
          #\s*renovate:\s*depName=(?<depName>[a-zA-Z0-9_-]+)\s+datasource=rubygems\s*\n\s*ENV\s+RUBYGEM_[A-Z0-9_-]+=\$\{RUBYGEM_[A-Z0-9_-]+:-?(?<currentValue>[^}\n]+)\}
    - customType: regex
      datasourceTemplate: rubygems
      versioningTemplate: ruby
      managerFilePatterns:
        - /build_platforms.yaml/
      matchStrings:
        - >-
          #\s*renovate:\s*depName=(?<depName>[a-zA-Z0-9_-]+)\s+datasource=rubygems\s*\n\s*(?<key>openvox_version):\s*'(?<currentValue>[^']+)'
  renovate_custom_datasources: {}
  renovate_package_rules: []

RELEASE.md:
  release_preamble:
.github/workflows/ci.yml:
  general_ci_scan_dir:
  build_job_name: Build ci container
  test_repository:
  test_commands: []
  post_test_commands: []
.github/workflows/security_scanning.yml:
  scan_job_name: Scan ci container
  fail_build: false
  severity_cutoff:
  sarif_category:
.github/workflows/build_container.yml:
  publish_tag_patterns:
    - '*'
  publish_schedules: []
  publish_runner:
  publish_build_job_name: Build and publish container
  publish_build_arch: 'linux/amd64,linux/arm64'
  publish_tags: []
  publish_pre_build_steps: []
  publish_setup_outputs: {}
  publish_setup_steps: []
  publish_manifest_matrix_command:
  publish_manifest_steps: []
  publish_attestation_subject:
  publish_info_container:
  publish_info_commands: []
  publish_vulnerability_issue_image:
  dockerhub_repository:
