---
name: 🚀 Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  release:
    name: Release
    uses: voxpupuli/crafty/.github/workflows/release.yml@main
    with:
      allowed_owner: <%= @configs[:namespace] %>
