---
name: 🚀 Create GitHub Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  release:
    name: Create GitHub Release
    if: ${{ github.repository_owner == 'voxpupuli' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release Page
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --repo ${{ github.repository }} ${{ github.ref_name }} --generate-notes
