name: 🤖 Update

on:
  workflow_dispatch: {}

jobs:
  update-all-voxpupuli-modules:
    runs-on: ubuntu-latest
    name: "🦊 Vox Pupuli: msync all"
    steps:
      - uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run msync
        env:
          GIT_COMMITTER_NAME: 'VoxBox'
          GIT_COMMITTER_EMAIL: 'voxbot@voxpupuli.org'
          GIT_AUTHOR_NAME: 'VoxBox'
          GIT_AUTHOR_EMAIL: 'voxbot@voxpupuli.orgm'
        run: |
          git config --global user.name "VoxBot"
          git config --global user.email "voxbot@voxpupuli.org"
          export GITHUB_TOKEN=${{ secrets.VOXPUPULI_PAT }}
          bundle exec msync update \
            --pr \
            --pr-labels modulesync \
            --pr-title Modulesync \
            --git-base="https://github.com/"
